# CS 412, Homework 1, Wenke Huang (whuang67)
### Question 1

*1.*

The largest eigenvector of the covariance matrix points into the direction of the largest variance. Or other eigenvectors are orthogonal to the largest one. The eigenvectors are also called principal components and are sorted from in the order of decreasing strength. The size of the data can also be reduced by eliminating the weak principal components.

*2.*

In [1]:
import numpy as np
matrix = np.array([[2,0,0], [0,3,4], [0,4,9]])
## a (Yes)
a = np.array([1,0,0])
print matrix.dot(a)
## b (Yes)
b = np.array([0,1,2])
print matrix.dot(b)
## c (No)
c = np.array([1,1,1])
print matrix.dot(c)

[2 0 0]
[ 0 11 22]
[ 2  7 13]


When $\lambda=2$, we have $\mathbf{Aa}=\lambda\mathbf{a}$. When $\lambda=11$, we have $\mathbf{Ab}=\lambda\mathbf{b}$. But we cannot find any value $\lambda$ that makes $\mathbf{Ac}=\lambda\mathbf{c}$ be True.

Hence, vector $\mathbf{a}$ and $\mathbf{b}$ are eigenvectors while $\mathbf{c}$ is not. The eigenvalues of vector $\mathbf{a}$ and $\mathbf{b}$ are 2 and 11, respectively.

### Question 2

Rolling up, Slicing and Dicing can be operated here. First, we can roll up on Time (from day to year). Then, we can slice on Patient. Here, we would like to sum the fees of different Patients together. Hence, we can have the annual total fee collected by each doctor. Last, we can dice on the year of 2010, which gives us a list of the total fee collected by each doctor in 2010.

### Question 3

*1.*

$2^{10}=1024$. The full data cube contains 1024 nonempty cuboids.

*2.*

Each cell generates $2^{10}-1=1023$ nonempty aggregated cells, and hence, totally we have $3\times1023=3069$ nonempty aggregated cells before we remove the overlapped ones. We have $3\times2^7$ cells overlapped once and $1\times2^7$ cells overlapped twice. Hence, we should remove $3\times2^7+2\times1\times2^7=640$ overlapped cells.

We should have $3069-640=2429$ nonempty aggregated cells.

*3.*

(*,*,d3,d4,...,d10):2, (*,d2,*,d4,...,d10):2, (d1,*,*,d4,...,d10):2, (*,*,*,d4,...,d10):3

Hence, we should have $4\times2^7=512$ cells which follow the reguirement.

### Question 4

*1. (a)*

We would like to keep the smallest plane in main memory. In this case, it should be **BC**. Fetch and compute only one chunk at a time for the largest plane which is **AC**. The planes should be sorted and computed according to their size in ascending orders.

In this case, it should first aggregate towards **AC** plane, then towards **AB** plane and lastly towards **BC** plane. If we use the number of chucks, it should be (1, 10, 19, 4, 13, 22, 7, 16, 25, 2, 11, 20, 5, 14, 23, 8, 17, 26, 3, 12, 21, 6, 15, 24, 9, 18, 27).

*(b)*

The minimum memory requirement for holding all the 2-D planes is $300\times600+300\times300+300\times200=330000$. (The whole **BC** plane, one row of the **AB** plane and one chunk of the **AC** plane)

*2.*

In [2]:
tree = """(a)
The trace tree of expansion:
        All 
        /|\ 
       C B A 
      / \ \ 
     CB CA BA 
    /
   CBA
   
Remark: In this case, CB will not be expanded to CBA since its count is less than min_sup which is 4."""

compute = """
(b)
All (*,*,*): 16 - expansion
-------
 C (*,*,c0): 5 - expansion
 C (*,*,c1): 5 - expansion
 C (*,*,c2): 6 - expansion
 -------
  CB (*,b0,c0): 1
  CB (*,b1,c0): 2
  CB (*,b2,c0): 1
  CB (*,b3,c0): 1
  CB (*,b0,c1): 1
  CB (*,b1,c1): 1
  CB (*,b2,c1): 2
  CB (*,b3,c1): 1
  CB (*,b0,c2): 1
  CB (*,b1,c2): 1
  CB (*,b2,c2): 1
  CB (*,b3,c2): 3
 -------
  CA (a0,*,c0): 3
  CA (a1,*,c0): 2
  CA (a0,*,c1): 2
  CA (a1,*,c1): 3
  CA (a0,*,c2): 2
  CA (a1,*,c2): 4
-------
 B (*,b0,*): 3
 B (*,b1,*): 4 - expansion
 B (*,b2,*): 4 - expansion
 B (*,b3,*): 5 - expansion
 -------
  BA (a0,b1,*): 4
  BA (a1,b2,*): 4
  BA (a1,b3,*): 5
-------
 A (a0,*,*): 7
 A (a1,*,*): 9
"""
print tree
print compute
number = len(compute.split("\n"))-len(compute.split("-\n"))-2
print "{} cells would be computed given the exploration order and min_sup.".format(number)

(a)
The trace tree of expansion:
        All 
        /|\ 
       C B A 
      / \ \ 
     CB CA BA 
    /
   CBA
   
Remark: In this case, CB will not be expanded to CBA since its count is less than min_sup which is 4.

(b)
All (*,*,*): 16 - expansion
-------
 C (*,*,c0): 5 - expansion
 C (*,*,c1): 5 - expansion
 C (*,*,c2): 6 - expansion
 -------
  CB (*,b0,c0): 1
  CB (*,b1,c0): 2
  CB (*,b2,c0): 1
  CB (*,b3,c0): 1
  CB (*,b0,c1): 1
  CB (*,b1,c1): 1
  CB (*,b2,c1): 2
  CB (*,b3,c1): 1
  CB (*,b0,c2): 1
  CB (*,b1,c2): 1
  CB (*,b2,c2): 1
  CB (*,b3,c2): 3
 -------
  CA (a0,*,c0): 3
  CA (a1,*,c0): 2
  CA (a0,*,c1): 2
  CA (a1,*,c1): 3
  CA (a0,*,c2): 2
  CA (a1,*,c2): 4
-------
 B (*,b0,*): 3
 B (*,b1,*): 4 - expansion
 B (*,b2,*): 4 - expansion
 B (*,b3,*): 5 - expansion
 -------
  BA (a0,b1,*): 4
  BA (a1,b2,*): 4
  BA (a1,b3,*): 5
-------
 A (a0,*,*): 7
 A (a1,*,*): 9

31 cells would be computed given the exploration order and min_sup.
